// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bB2oXvbmu-M2ncoPTKEGPCvQwoMUYQM',
    appId: '1:511795380278:web:0f5e9de0583b7bd4bdd897',
    messagingSenderId: '511795380278',
    projectId: 'safarday-driver',
    authDomain: 'safarday-driver.firebaseapp.com',
    storageBucket: 'safarday-driver.appspot.com',
    measurementId: 'G-WNPBBGWWPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKtNXEj1gwezfqMt1xZg_V0tVynVRrc7M',
    appId: '1:511795380278:android:75d8fc2b1052805ebdd897',
    messagingSenderId: '511795380278',
    projectId: 'safarday-driver',
    storageBucket: 'safarday-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYO4Wdb-jR4pxNnbFh3xMHIBWfKLdxxLs',
    appId: '1:511795380278:ios:5b5856ab1d0cd600bdd897',
    messagingSenderId: '511795380278',
    projectId: 'safarday-driver',
    storageBucket: 'safarday-driver.appspot.com',
    iosBundleId: 'com.pishranesh.transportationdriver',
  );
}
